# Generated by Django 5.0.1 on 2024-01-04 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='make',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='model_type',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car_make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.carmake'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car_model',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Wagon', 'Station wagon'), ('Sport', 'Sports Car'), ('Coupe', 'Coupe'), ('Mini', 'Mini van'), ('Van', 'Van'), ('Pickup', 'Pick-up truck'), ('Truck', 'Truck'), ('Other', 'Other')], default='SUV', max_length=100),
        ),
        migrations.AlterField(
            model_name='carmake',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='dealer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
